blog/urls.py
from django.urls import path

#local import
from . import views

app_name="blog"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('<slug:slug>/', views.detail, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import blog.views

urlpatterns = [
    path('', blog.views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify

from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):
    title = models.CharField(default='', max_length=255)
    description = models.TextField(default='', blank=True)
    slug = models.SlugField(default='', blank=True, max_length=255)
    create_date = models.DateTimeField(auto_now_add=True, null=True)
    modified_date = models.DateTimeField(auto_now=True, null=True)
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    tags = TaggableManager()
    
    def __str__(self):
        return self.title

    # slug is a short label thet is used in URLs, it can only use letters, numbers,hyphens and underscores
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.slug)])
 
    

blog/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'description',
            'slug',
            'tags',
        ]

class PostDeleteForm(ModelForm):
    class Meta:
        model = Post
        fields = []

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import permission_required

from .models import Post
from .forms import PostForm, PostDeleteForm

# Create your views here.
def home(request):
    posts = Post.objects.all()
    context = {'page':'home', 'posts': posts}
    return render(request, 'home.html', context)

def detail(request, slug=None):
    
    post = get_object_or_404(Post, slug=slug)

    context = {'page': 'blog_detail', 'post': post}
    
    return render(request, 'blog/detail.html', context)

@permission_required('blog.add_post', raise_exception=True)
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('home')
    else:
        form = PostForm()
    context = {'page': 'blog_create', 'form': form,}
    return render(request, 'blog/create.html', context)   

@permission_required('blog.change_post', raise_exception=True)
def edit(request, pk=None):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
        context = {
            'page' : 'blog_edit',
            'form' : form,
            'post' : post
        }
        return render(request, 'blog/edit.html', context)

@permission_required('blog.delete_post', raise_exception=True)
def delete(request, pk=None):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostDeleteForm(request.POST, instance=post)
        if form.is_valid():
            post.delete()
            return redirect('home')
    else:
        form = PostDeleteForm(instance=post)
    context = {
        'page' : 'blog_delete',
        'form' : form,
        'post' : post,
    }
    return render(request, 'blog/delete.html', context)

blog/templates/blog/create.html
{% extends 'base.html' %}

{% block title %}Add new post{% endblock %}

{% block content %}
    <form action="{% url 'blog:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Create</button>
    </form>
{% endblock %}

blog/templates/blog/delete.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <form action="{% url 'blog:delete' post.pk %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <p>Are you sure you want to delete this post:</p>
        <br>
        <a href="{% url 'blog:detail' post.slug %}">
            {{ post.title }} : {{ post.description }}
        </a>
        <br>
        <button class="btn btn-danger" type="submit">Delete</button>
        <a href="{% url 'home' %}">Cancel</a>
    </form>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    {% if post %}
        <h1>{{ post.title }}</h1>
        <p>Posted {{ post.create_date|date:"M j, Y" }}</p>
        <p>Updated {{ post.modified_date }}</p>
        {% if post.author %} 
            <p>{{ post.author }}</p>
        {% endif %}
        <p>{{ post.description }}</p>
    {% endif %}

{% endblock %}

blog/templates/blog/edit.html
{% extends 'base.html' %}

{% block title %}You are editing: {{ post.title }}{% endblock %}

{% block content %}
    <form action="{% url 'blog:edit' post.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary" type="submit">Update</button>
        <a href="{% url 'home' %}">Cancel</a>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css?v=01" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
    <title>Django Blog | {% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Blog App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if page == 'home' %} active {% endif%}" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              {% if perms.blog.add_post %}
                <a class="nav-link {% if page == 'blog_create' %} active {% endif%}" aria-current="page" href="{% url 'blog:create' %}">Add new post</a>
              {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="#">Item</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="#">Another Item</a>
            </li>
            <li class="nav-item">
              {% if not user.is_authenticated %}
                <a class="nav-link" aria-current="page" href="{% url 'account_login' %}">Sign In</a>
              {% else %}
                <a class="nav-link" aria-current="page" href="{% url 'account_logout' %}">Sign Out</a>
              {% endif %}
              </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

        {% block content %}
        {% endblock %}

    </div>
    <div class="container mt-5">
      <p class="text-center">Copyright &copy;Django.com | All Rights Reserved</p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
  
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Blog Posts</h1>
    
    {% if posts %}
        {% for post in posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.pk }} : {{ post.title }}</a> 
                <span>
                    {% if perms.blog.change_post %}
                        [<a href="{% url 'blog:edit' post.pk %}">Edit</a>]
                    {% endif %}
                </span>  
                <span>
                    {% if perms.blog.delete_post %}
                        [<a href="{% url 'blog:delete' post.pk %}">Delete</a>]
                    {% endif %}
                </span>      
            </p>
        {% endfor %}
    {% endif %}

{% endblock %}